language: php

branches:
  # Only test the master branch and semantic version tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  include:
    - php: 7.0
      env: dependencies=highest
    - php: 5.6
    - php: 5.5
      env: dependencies=lowest

sudo: false

env:
  global:
    - TERMINUS_TEST_MODE=1
    - COMPOSER_PROCESS_TIMEOUT=3600

before_script:
  - set -ex
  - if [ -z "$dependencies" ]; then composer install -n --prefer-dist; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update -n --prefer-dist --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n --prefer-dist -n; fi;

script:
  - composer clover
  - phpenv config-rm xdebug.ini # XDebug is needed for code coverage, but makes things slow. It's enabled by default in Travis, we disable it here post-coverage run for speedy builds.
  - composer cs
  - composer phpunit
  - composer behat

after_success:
    - if [ $(phpenv version-name) = "7.0" ]; then composer coveralls; fi

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache
