---
name: Catalog

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 3.x

permissions:
  contents: "read"
  packages: "read"
  id-token: "write"

jobs:
  # TODO: enable docs-like-code once we are ready to publish docs to Confluence
  # docs:
  #   uses: pantheon-systems/service-catalog/.github/workflows/docs-like-code.yaml@main
  catalog-upload:
    uses: pantheon-systems/service-catalog/.github/workflows/catalog-upload.yaml@main